### ISSUE TITLE
Не могу воспользоваться пакетом из-за низкой версии Flutter

### ISSUE THREAD

**Issue by moisey312** [meg4cyberc4t/varioqub_configs#14]
```
The current Dart SDK version is 3.1.3.

Because app depends on varioqub_configs >=0.0.2 which requires SDK version >=3.2.0 <4.0.0, version solving failed.

```

Есть ли какое-то объяснение завышенным версиям пакета? Если нет - не затруднит ли вас понизить версию?

**Comment by meg4cyberc4t** [comment]
Привет. Спасибо за issue.
Я проведу исследование, можно ли понизить версию и вернусь с ответом чуть позже.

**Comment by meg4cyberc4t** [comment]
Опустил версию Dart до 3.0.0. Обновите версию библиотеки до 0.6.2
