### ISSUE TITLE
В новой версии 0.7.2 возникает ошибка при использовании с AppMetrica

### ISSUE THREAD

**Issue by moisey312** [meg4cyberc4t/varioqub_configs#21]
Попытался обновить версию varioqub_configs. После чего наткнулся на проблему с pod-ами.
При запуске `pod install` возникает ошибка `The 'Pods-Runner' target has frameworks with conflicting names: yandexmobilemetrica.xcframework.`, которая в последствии влияет на запуск. Понятно что возникает это из-за одновременного использования 2 пакетов('appmetrica_plugin' - официальный плагин и varioqub_configs), но непонятно что с этим делать

**Comment by meg4cyberc4t** [comment]
Привет. Какая версия пакета appmetrica_plugin? Попробуйте обновить до 2.0.0 и выше.
Проблема похоже на это [issue](https://github.com/meg4cyberc4t/varioqub_configs/issues/17)

**Comment by moisey312** [comment]
Благодарю за быстрый ответ и решение
