### ISSUE TITLE
Bad Request на IOS

### ISSUE THREAD

**Issue by moisey312** [meg4cyberc4t/varioqub_configs#22]
Не подключается к Varioqub на IOS, выходит:

> com.varioqub.network: start request: POST https://app.uaas.yandex.ru/v1/app?client_id=appmetrica.
com.varioqub.network: finish request: serverError(Varioqub.ServerResponse(body: Optional(22 bytes), statusCode: Varioqub.NetworkStatusCode(rawValue: 400), headers: Varioqub.NetworkHeaders(rawValues: ["Access-Control-Allow-Origin": "*", "Content-Type": "application/text", "Content-Encoding": "gzip", "Set-Cookie": "_yasc=rCo61e6Mgd+tauna20zCw/fbCE3DELsdhBtH7nCczAo8aQaKp38dO7IlyVnogAAe; domain=.yandex.ru; path=/; expires=Sat, 15 Apr 2034 06:19:16 GMT; secure", "Transfer-Encoding": "Identity"])))

Реализация:
```
class VarioqubService {
  final varioqub = VarioqubConfigs();

  Future<void> init() async {
    await varioqub.build(
      BuildSettings(
        client: VarioqubClient.appmetrica(EnvironmentConfig.APPMETRICA_ID),
      ), // Your AppMetrica application ID
    );
    try {
      await varioqub.activateConfig();
      await varioqub.fetchConfig();
    } catch (e) {
      Sentry.captureException('Не удалось загрузить Varioqub сервисы');
    }
  }

  Future<String> getId() async => await varioqub.getId();

  Future<String> get testString async => await varioqub.getString(key: 'test_string', defaultValue: 'default_string');

  Future<bool> get testBool async => await varioqub.getBool(key: 'test_bool', defaultValue: false);

  Future<int> get testInt async => await varioqub.getInt(key: 'test_int', defaultValue: 0);
}
```

На Android при этой же реализации все работает

**Comment by moisey312** [comment]
Поправил, но по прежнему не получаю конфигов, только дефолтные

**Comment by moisey312** [comment]
Также ваш код выдает дефолтное значение на вашем example с моим appmetrica_id

**Comment by meg4cyberc4t** [comment]
Конфиги работают в следующем порядке:
- берётся дефолтное значение, оно используется по умолчанию
- если есть скачанный и активированный конфиг (fetch, а потом activate), значения будут использоваться из конфигурации.
В примере example прописано специально сначала активировать старый конфиг (если он был скачан), следом fetch нового конфига. В первый запуск приложения будут показываться дефолтные значения - это ожидаемое поведение. При использовании приложения ещё раз, конфиги будут активироваться и вы должны увидеть свои значения.

**Comment by moisey312** [comment]
Данный экзампл очень запутал, но спасибо за ответ
